services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=advanceQuery'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=root'
    ports:
      - "6543:5432"
    volumes:
      - advance-query:/var/lib/postgresql/data
volumes:
  advance-query: